### ISSUE TITLE
Pyrogram 1.4.0 Error

### ISSUE THREAD

**Issue by yeathn** [joel122002/telegram-outgoing-call-with-audio#2]
I couldnt get it to work with Pyrogram 1.4.0. I tried using Pyrogram 2.0.106 after reading that it fixes the "pyrogram.errors.BadMsgNotification: [16] The msg_id is too low, the client time has to be synchronized." error, which I had.

But sadly couldnt get it working.

**Comment by joel122002** [comment]
What's the exact issue with 1.4.0?

**Comment by lau414** [comment]
I'm getting the same error `pyrogram.errors.BadMsgNotification: [16] The msg_id is too low, the client time has to be synchronized`. On the internet people fix it by updating pyrogram to version 2.0.106, however then the code doesn't work and I get the error `AttributeError: 'Client' object has no attribute 'send'`. I have tried other versions of pyrogram < 2 but I get the same error in all of them.

**Comment by joel122002** [comment]
Can you try [this](https://github.com/Dineshkarthik/telegram_media_downloader/issues/446#issuecomment-1595644384) and report how it works?

**Comment by lau414** [comment]
Yes, that was the first thing I tried. That solution installs version 2.0.106 of pyrogram  so I get the error `AttributeError: 'Client' object has no attribute 'send'` that I mentioned

**Comment by joel122002** [comment]
From what I read if you clear the session it should work

**Comment by lau414** [comment]
I already deleted every time the .session that is created before trying the solutions but sadly I still get the same errors

**Comment by joel122002** [comment]
I currently do not have the bandwidth to look into this. I'll look into it later and let you know

**Comment by lau414** [comment]
I found the solution to resolve the `AttributeError: 'Client' object has no attribute 'send'` error. I found out that in version 2.0.106 of pyrogram the send method is now called invoke but pytgvoip_pyrogram still calls it as sent (as mentioned [here ](https://github.com/bakatrouble/pytgvoip_pyrogram/issues/13#issuecomment-1890157056)). I debugged the libraries and corrected the references to that function.

However, I have not been able to get it to work yet. I'm trying to make the automated telegram call from a bot I created. So when it asks me for the phone number or bot token, I provide the token. However, I get the following error message `The method can't be used by bots (caused by "messages.GetDhConfig")`. 

Did the program ever work with a bot? Or was it only tested with a user? When testing with my user before, my Telegram account was blocked due to too many attempts, so if that is a recurring problem I don't see it viable to use the user, so I tried to use the bot, but as I said, without success. Maybe is a problem with pytgvoip_pyrogram library again and can be solved manually but I can't find the origin.

Edit: Finally I have been able to get it work with a user but not with a bot.

**Comment by joel122002** [comment]
Could you possibly post your working solution somewhere so that people can have a reference?
